apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: kubectl
    image: joshendriks/alpine-k8s
    command:
    - /bin/cat
    tty: true    
    volumeMounts:
      - name: frontend-secret
        mountPath: /frontend/.docker
  volumes:
    - name: frontend-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
